#!/usr/bin/env python3
import os, glob
import mimetypes

#E-Mail
import email, smtplib, ssl

from email import encoders
from email.mime.base import MIMEBase
from datetime import date
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

studID = "EliDerDeli"

#pdf input
pw = input("Type in your pdf name which will be attached, please")

#creates E-Mail
myEMail = MIMEMultipart()
sender = "EliDerDeli@gmail.com"
myEMail['From'] = sender
reciever  = "{}@gmail.com".format(str(studID))
myEMail['To'] = reciever
myEMail['Subject']  = "from Python with love, TEST E-MAIL"
bod = "Hello, Im a test mail generated by a simple Python Script. Delete me"
myEMail.attach(MIMEText(bod, "plain"))

#create an E-Mail attachment (Attach my PDF from the reports script)
filename = str(pw)

# Open PDF file in binary mode
with open(filename, "rb") as attachment:
    # Add file as application/octet-stream
    # Email client can usually download this automatically as attachment
    part = MIMEBase("application", "octet-stream")
    part.set_payload(attachment.read())

# Encode file in ASCII characters to send by email    
encoders.encode_base64(part)

myEMail.attach(part)
text = myEMail.as_string()

pwR = input("Please enter now the Password")

# inits mail server for sending
# Log in to server using secure context and send email
context = ssl.create_default_context()
with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
    server.login("EliDerDeli@gmail.com", pwR)
    server.sendmail(sender, reciever, text)
